// Generated by js_of_ocaml 2.5
(function caesar (C){"use strict";var
m=1024,j=128,d="",q=" : file already exists",a=248,u="/",v="fd ";function
M(a,b){throw[0,a,b]}function
P(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
X(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
t(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=m,c-=m)f+=e.apply(null,X(a,b,Math.min(c,m)));return f}function
E(a){if(a.t==2)a.c+=P(a.l-a.c.length,"\0");else
a.c=t(a.c,0,a.c.length);a.t=0}function
H(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
U(a){for(var
l=d,e=d,h,g,i,b,c=0,k=a.length;c<k;c++){g=a.charCodeAt(c);if(g<j){for(var
f=c+1;f<k&&(g=a.charCodeAt(f))<j;f++);if(f-c>512){e.substr(0,1);l+=e;e=d;l+=a.slice(c,f)}else
e+=a.slice(c,f);if(f==k)break;c=f}b=1;if(++c<k&&((i=a.charCodeAt(c))&-64)==j){h=i+(g<<6);if(g<224){b=h-12416;if(b<j)b=1}else{b=2;if(++c<k&&((i=a.charCodeAt(c))&-64)==j){h=i+(h<<6);if(g<240){b=h-925824;if(b<2048||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((i=a.charCodeAt(c))&-64)==j&&g<245){b=i-63447168+(h<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;e+="\ufffd"}else
if(b>65535)e+=String.fromCharCode(55232+(b>>10),56320+(b&1023));else
e+=String.fromCharCode(b);if(e.length>m){e.substr(0,1);l+=e;e=d}}return l+e}function
T(a){switch(a.t){case
9:return a.c;default:E(a);case
0:if(H(a.c)){a.t=9;return a.c}a.t=8;case
8:return U(a.c)}}function
i(a,b,c){this.t=a;this.c=b;this.l=c}i.prototype={toString:function(){return T(this)}};function
c(a){return new
i(0,a,a.length)}function
B(a,b){M(a,c(b))}var
e=[0];function
f(a){B(e[2],a)}function
I(a){if(!a.opened)f("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
y(a){B(e[4],a)}function
k(a){if(a<0)y("String.create");return new
i(a?2:9,d,a)}function
g(a){this.data=a}g.prototype={truncate:function(){this.data=k(0)}};function
s(a){return a.l}function
A(a){a=a
instanceof
i?a.toString():a;f(a+": No such file or directory")}var
F=u;function
n(a){a=a
instanceof
i?a.toString():a;if(a.charCodeAt(0)!=47)a=F+a;var
e=a.split(u),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
h(){this.content={}}h.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
p=new
h();p.mk(d,new
h());function
r(a){var
b=p;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))A(a.orig);b=b.get(a[c])}return b}function
S(a){var
c=n(a),b=r(c);return b
instanceof
h?1:0}function
Q(a){return new
i(4,a,a.length)}function
x(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
Y(a){if(a.t!=4)x(a);return a.c}function
G(a,b){var
j=n(a),d=p;for(var
k=0;k<j.length-1;k++){var
e=j[k];if(!d.exists(e))d.mk(e,new
h());d=d.get(e);if(!(d
instanceof
h))f(j.orig+q)}var
e=j[j.length-1];if(d.exists(e))f(j.orig+q);if(b
instanceof
h)d.mk(e,b);else
if(b
instanceof
g)d.mk(e,b);else
if(b
instanceof
i)d.mk(e,new
g(b));else
if(b
instanceof
Array)d.mk(e,new
g(Q(b)));else
if(b.toString)d.mk(e,new
g(c(b.toString())));else
y("caml_fs_register");return 0}function
R(a){var
b=p,d=n(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
l(a,b,c){if(e.fds===undefined)e.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?s(b.data):0;d.flags=c;e.fds[a]=d;e.fd_last_idx=a;return a}function
Z(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=n(a);if(d.rdonly&&d.wronly)f(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)f(h+" : flags Open_text and Open_binary are not compatible");if(R(a)){if(S(a))f(h+" : is a directory");if(d.create&&d.excl)f(h+q);var
i=e.fd_last_idx?e.fd_last_idx:0,g=r(j);if(d.truncate)g.truncate();return l(i+1,g,d)}else
if(d.create){var
i=e.fd_last_idx?e.fd_last_idx:0;G(a,k(0));var
g=r(j);return l(i+1,g,d)}else
A(a)}l(0,new
g(k(0)));l(1,new
g(k(0)));l(2,new
g(k(0)));function
J(a){var
b=e.fds[a];if(b.flags.wronly)f(v+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
w(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?t(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?t(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)x(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
V(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=C.console;b&&b.error&&b.error(a)}function
W(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=C.console;b&&b.log&&b.log(a)}var
o=new
Array();function
O(a,b){var
h=c(b),d=s(h),g=s(a.file.data),f=a.offset;if(f+d>=g){var
e=k(f+d);w(a.file.data,0,e,0,g);w(h,0,e,f,d);a.file.data=e}a.offset+=d;return 0}function
z(a){var
b;switch(a){case
1:b=W;break;case
2:b=V;break;default:b=O}var
g=e.fds[a];if(g.flags.rdonly)f(v+a+" is readonly");var
c={file:g.file,offset:g.offset,fd:a,opened:true,buffer:d,output:b};o[c.fd]=c;return c}function
K(){var
a=0;for(var
b
in
o)if(o[b].opened)a=[0,o[b],a];return a}function
b(a,b){e[a+1]=b}var
L=0;function
N(a){a[2]=L++;return a}b(11,[a,c("Undefined_recursive_module"),-12]);b(10,[a,c("Assert_failure"),-11]);b(9,[a,c("Sys_blocked_io"),-10]);b(8,[a,c("Stack_overflow"),-9]);b(7,[a,c("Match_failure"),-8]);b(6,[a,c("Not_found"),-7]);b(5,[a,c("Division_by_zero"),-6]);b(4,[a,c("End_of_file"),-5]);b(3,[a,c("Invalid_argument"),-4]);b(2,[a,c("Failure"),-3]);b(1,[a,c("Sys_error"),-2]);b(0,[a,c("Out_of_memory"),-1]);N([a,c("Pervasives.Exit"),0]);J(0);z(1);z(2);function
D(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{I(d)}catch(f){}var
b=c;continue}return 0}}D(K(0));return}(function(){return this}()));
